### ISSUE TITLE
SDK should return `Observables` rather than `Promises`

### ISSUE THREAD

**Issue by brionmario** [asgardeo/asgardeo-auth-angular-sdk#101]
**Is your suggestion related to an experience ? Please describe.**
ATM, most of the APIs return `Promises` which is not a common angular pattern.

**Describe the improvement**
We need to modify the SDK to return `Observables` instead.

**Additional context**
`RxJs` operators could be used to convert promises to observables.

**IMPORTANT** - A Major version should be released along with these changes since this would be a breaking change.

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
