### ISSUE TITLE
Encourage the library authors to publish an Ivy distribution.

### ISSUE THREAD

**Issue by chrissierra** [asgardeo/asgardeo-auth-angular-sdk#116]
**Describe the issue:**

- @asgardeo/auth-angular [es2015/esm2015] (git+https://github.com/asgardeo/asgar
deo-auth-angular-sdk.git)
Encourage the library authors to publish an Ivy distribution.

**How to reproduce:**

Installing library
**Expected behavior:**

Get installed .
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - OS: [e.g., Windows, Linux, Mac]
 - SDK Version: [e.g., 0.1.0, 0.1.1]
Windows 10
---

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
