### ISSUE TITLE
npm is not up to date with the latest version.

### ISSUE THREAD

**Issue by chrissierra** [asgardeo/asgardeo-auth-angular-sdk#124]
**Describe the issue:**

There was a bug where there was a loop after login, that was fixed with:

         if (!SPAUtils.hasAuthSearchParamsInURL(this.navigator.getCurrentUrl())) {
             this.auth.signIn();
         }
However, the latest version of npm does not have such a fix implemented.

how can i use the latest version in an angular project then ?

**Comment by thivi** [comment]
Hi @chrissierra,
Are you by any chance trying to sign a user in on page load? If that is the case, you need to make sure `this.auth.signIn()` is called only if `isLoading` attribute of the `state` object is set to `false`;

For example:
```
this.auth.state$.subscribe((state) => {
   if(state.isLoading) {
      this.auth.signIn();
   }
});    
```

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
