### ISSUE TITLE
isAuthenticated returns true, even though access token is expired

### ISSUE THREAD

**Issue by aaptl** [asgardeo/asgardeo-auth-angular-sdk#129]
**Current behavior:**

isAuthenticated returns true, even though the token is expired.

**Expected behavior:**
isAuthenticated returns false when the token is expired.

**How to reproduce:**

After Application authentication i am waiting to expire access token then i am trying to check isAuthenticated()
 await this.auth.isAuthenticated();
 https://github.com/asgardeo/asgardeo-auth-angular-sdk/releases/latest/download/asgardeo-angular-app.zip
 Please use above link to test the issue
 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - OS: Windows
 - SDK Version: 3.6

**Comment by thivi** [comment]
Hi @aaptl,
`isAuthenticated` returns `false` only if the user is unauthenticated or has signed out. This does not state anything regarding the validity of the token.

**Comment by aaptl** [comment]
Hi @thivi 
How we will do auto logout if access token expires, i tried state observable in Auth guard but not working as expected.

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
