### ISSUE TITLE
Angular Authentication SDK & Samples

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#3]
**Is your feature request related to a problem? Please describe.**

As of now, Asgardeo / Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate angular application with IS.

Having an official SDKs, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on

- Selecting and applying best practices on different authentication protocols
- Selecting correct libraries to implement
- Make that client-side implementation to integrated with IS

**Describe the solution you would prefer**

Have an Angular SDK, sample, and needed guides to integrate the application with Asgardeo / Identity Server.

**Additional context**

Effort FE::119	

**Tasks**

- [Angular Authentication (OIDC) SDK Development](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/4)
- [Developer Documentation for Angular SDK](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/16)
- [Sample to Demonstrate the Usage of the SDK](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/17)
- [Unit Tests with Karma & Jasmine](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/18)
- Integration Testing with Cypress
- Support for Angular Schematics

**Comment by DonOmalVindula** [comment]
Closing the issue as the `asgardeo-auth-angular-sdk` will be deprecated and archived.
