### ISSUE TITLE
SDK Throws a Type Error for Angular Version 11 Strict mode

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#48]
**Describe the issue:**

```
Error: node_modules/@asgardeo/auth-spa/dist/src/models/web-worker.d.ts:25:5 - error TS2416: Property
 'onmessage' in type 'WebWorkerClass<T>' is not assignable to the same property in base type 'Worker'.
  Type '(this: WebWorkerClass<T>, event: WebWorkerEvent<T>) => any' is not assignable to type 
   '(this: Worker, ev: MessageEvent<any>) => any'.
    The 'this' types of each signature are incompatible.
     Type 'Worker' is not assignable to type 'WebWorkerClass<T>'.
      Types of property 'onmessage' are incompatible.
       Type '((this: Worker, ev: MessageEvent<any>) => any) | null' is not assignable to type 
        '(this: WebWorkerClass<T>, event: WebWorkerEvent<T>) => any'.
         Type 'null' is not assignable to type '(this: WebWorkerClass<T>, event: WebWorkerEvent<T>) => any'.
```

**How to reproduce:**

1. Create an angular app with @angular/cli v 11 [strict mode](https://angular.io/guide/strict-mode) enabled 
2. Import @asgardeo/auth-angular `AsgardeoAuthModule`
3. Serve the app

**Expected behaviour:**

SDK should not throw type errors for applications using **angular 11 strict mode** 

**Environment information:**

 - SDK Version: 0.1.2
 - Angular Version: 11 - strict mode
 
 ---
 
 **Temporary Solution:**
 
 Put warning labels for the use of `@asgardeo/auth-angular` in **angular 11 strict mode**

**Comment by JanithGan** [comment]
**Related PRs:**

- asgardeo/asgardeo-auth-spa-sdk#19 
- #74

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
