### ISSUE TITLE
Can't get TenantDomain

### ISSUE THREAD

**Issue by emilebui** [asgardeo/asgardeo-auth-angular-sdk#77]
**Describe the issue:**
There is no tenantDomain field from id_token after login

**How to reproduce:**
Run on WSO2IS 5.11.0 then click on login

**Expected behavior:**
There should be tenantDomain field in id_token

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: WSO2IS 5.11.0
 - OS: Window
 - SDK: latest
---

**Comment by thivi** [comment]
We are not returning the tenant domain in the ID token as of now. If you want to know the tenant domain, you can check `Use tenant domain in local subject identifier` under `Local & Outbound Authentication Configuration` on the edit view of the service provider in the carbon console. Then, the tenant domain will be appended to the subject identifier and you will be able to extract it using the [`getBasicUserInfo()`](https://github.com/asgardeo/asgardeo-auth-angular-sdk#getbasicuserinfo) method.

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
