### ISSUE TITLE
Latest releases of the SDK are not published to npm 

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#78]
**Describe the issue:**

> $subject

**How to reproduce:**

> Trigger the [release](https://github.com/asgardeo/asgardeo-auth-angular-sdk/actions/workflows/release.yml) github actions workflow

**Possible causes:**

> - Removing the npm token from repo secrets
> - Deleting the stored npm access token from asgardeo npm organization
> - Enabling two-factor authentication for asgardeo npm organization

---

**Environment information:**

> - SDK Version: v0.1.3, 0.1.4

**Comment by thivi** [comment]
Hi @JanithGan,
The release issue has been resolved by #87 and #88
