### ISSUE TITLE
Could not initiate token request when configuring wellknown endpoint for an external identity provider

### ISSUE THREAD

**Issue by piraveena** [asgardeo/asgardeo-auth-angular-sdk#80]
**Describe the issue:**
Added below code in the `app.module.ts`.

```
import {BrowserModule} from "@angular/platform-browser";
import {NgModule} from "@angular/core";
import {AppComponent} from "./app.component";

// Import Auth Module
import {AsgardeoAuthModule} from "@asgardeo/auth-angular";
import {Storage} from "@asgardeo/auth-spa";


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,

    // Provide the configs (See API Docs)
    AsgardeoAuthModule.forRoot({
      serverOrigin: "https://<idp_issuer_value>",
      signInRedirectURL: "https://localhost:4200",
      clientID: "<clientId>",
      wellKnownEndpoint: "/.well-known/openid-configuration",
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
Authorization code flow is working as expected. But token flow is not working. there is call to token endpoint in the network trace as well.

**AuthorizationRequest:**
`https://<idp_issuer_value>/authorize?response_type=code&client_id=<clientId>&scope=openid&redirect_uri=https%3A%2F%2Flocalhost%3A4200&response_mode=query&code_challenge_method=S256&code_challenge=-BAT5kFeMw6Mx9ZLZQf5xaW7W320eaiJqWbFJJHm9L0`

**Response:**
`https://localhost:4200/?code=5LjrbgCq8rce41wg`

**Comment by piraveena** [comment]
The root cause for this issue is, SDK depends on the session_state param to initiate the token request.

**Comment by thivi** [comment]
Resolved by https://github.com/asgardeo/asgardeo-auth-js-sdk/issues/35 and https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/36
