### ISSUE TITLE
Few Improvements on getBasicUserInfo api response

### ISSUE THREAD

**Issue by piraveena** [asgardeo/asgardeo-auth-angular-sdk#89]
**Is your suggestion related to an experience ? Please describe.**
We send below response when we call getBasicUserInfo()
```
{
  "allowedScopes": "openid",
  "sessionState": "977a152b3dc3584de549f150aed85d8e1a5bb62bc1e73d0c6f3516a69b608a1d.hsMArR21vaiMKvTRNgZ1Bw",
  "username": "alica@bifrost.com",
  "country": "Sri Lanka",
  "email": "alica@bifrost.com"
}
```

**Describe the improvement**
If we check the response send in getBasicUserInfo(), and since this is a user information related API response,
1. We should not send allowed scopes and sessionState along with this getBasicUserInfo() response. We can send those using other data models.
2. We should send 'sub' claim in this response.  We are assuming that  sub=username.

**Comment by brionmario** [comment]
`sub` was added to the response with the following PRs.

`asgardeo-auth-js-sdk` - https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/163
`asgardeo-auth-spa-sdk` - https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/64
`asgardeo-auth-react-sdk` - https://github.com/asgardeo/asgardeo-auth-react-sdk/pull/66
`asgardeo-auth-angular-sdk` - https://github.com/asgardeo/asgardeo-auth-angular-sdk/pull/105

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
