### ISSUE TITLE
Support OIDC userinfo 

### ISSUE THREAD

**Issue by piraveena** [asgardeo/asgardeo-auth-angular-sdk#90]
**Is your feature request related to a problem? Please describe.**
We are generating this `getBasicUserInfo()` response from idtoken, rather calling userinfo API.  
But it is better to have the support for userinfo API as well. Because all IDPs do not send all information in idtoken. 

**Describe the solution you would prefer**
Userinfo API support can be done as an improvement for SDK

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
