### ISSUE TITLE
The SDK version in Samples is not automatically bumped when a new release is made.

### ISSUE THREAD

**Issue by brionmario** [asgardeo/asgardeo-auth-angular-sdk#95]
**Describe the issue:**
$subject

**Expected behavior:**
Check https://github.com/asgardeo/asgardeo-auth-angular-sdk/releases/tag/v0.2.1.

Samples should have SDK version `v0.2.1.`.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - SDK Version: [e.g., 0.1.0, 0.1.1]

**Comment by DonOmalVindula** [comment]
Closing this issue since asgardeo-auth-angular-sdk will be deprecated and archived.
